### ISSUE TITLE
Hudkit going behind windows?

### ISSUE THREAD

**Issue by nferhat** [anko/hudkit#17]
The title explains the issue pretty clearly.

When opening hudkit with `hudkit https://localhost:5173` with a test red side bar, it displays above all windows.

When opening a new window, it goes behind the windows, like the following:
![image](https://user-images.githubusercontent.com/104871514/228672239-900729f1-a68e-4a41-8632-2a8ac72bb1a1.png)

Maybe it has todo with my window manager rules? I dont know, maybe add a rule that puts hudkit at the top?

Thanks.

**Comment by nferhat** [comment]
~~Fixed with some rules tweaking.~~

UPDATE: Still not working.

**Comment by anko** [comment]
What WM are you using? Hudkit uses [Extended Window Manager Hints](https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints) to tell the WM for example "this window should be on top of everything else". The article has a list of WMs that support that standard.

- With WMs supporting EWMH, no special configuration should be necessary.

- With WMs that don't support it, you need application-specific configuration. Some may have a "always keep these windows on top" option.

Stuff that might help with debugging: You can see all properties of the Hudkit window with `xwininfo -all -name "hudkit overlay window"`, which includes EWMH properties in the "Window manager hints" section.

**Comment by nferhat** [comment]
Hi, first and foremost, thanks alot for the answer!

The window managed used here is XMonad with support for EWMH, thoughs I don't have XMonad nor hudkit installed on my system right now. I'll install it later when I find time.

Thanks.
