### ISSUE TITLE
Feedback on using with Linux Mint (mentioning clang in dependencies is necessary?)

### ISSUE THREAD

**Issue by ghost** [anko/hudkit#9]
>If you build on another distro, I'm interested in how it went.

Went grrrreat!

Linux Mint x64 20.1 w/5.8.0-50 kernel.

Dependencies were installed with following commands successfully:
```
sudo apt-get install libgtk-3-dev
sudo apt-get install libwebkit2gtk-4.0
```

Make was failing with
```
clang -std=c11 main.c -o hudkit `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0`
/bin/sh: 1: clang: not found
make: *** [makefile:2: hudkit] Error 127
```
Solved with
`sudo apt-get install clang`
(clang probably should be listed in [Dependencies](https://github.com/anko/hudkit#dependencies))

run.sh sample script output:
![Screenshot from 2021-04-25 14-27-56](https://user-images.githubusercontent.com/81986452/115991724-7a63ad00-a5d2-11eb-907e-7e569a54981a.png)

Works brilliantly!

**Comment by anko** [comment]
Thanks for the details.  Looks as intended.  :sparkles: :clap::smile: :sparkles:

I added to the readme those packages for Mint, and a brief explanation of the C compilation tools needed.
